#Show inventory tabs
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
showTabs = false
#Show inventory tabs only in curio page. Only works when showTabs is true and curio is installed.
showTabsOnlyCurio = false
#Redirect Inventory Tab to Curios Inventory
redirectInventoryTabToCuriosInventory = false
<<<<<<< HEAD
=======
=======
showTabs = true
#Show inventory tabs only in curio page. Only works when showTabs is true and curio is installed.
showTabsOnlyCurio = false
#Redirect Inventory Tab to Curios Inventory
redirectInventoryTabToCuriosInventory = true
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
#Number of attribure lines per page
#Range: 1 ~ 100
attributeLinePerPage = 15
#List of tabs to hide. Use title translation key for tab id.
#Example: menu.tabs.attribute for attribute tab
#Example: menu.tabs.curios for curios tab
#Example: pandora.menu.title for pandora tab
hiddentTabs = []

