<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
# This is the configuration file for Embeddium.
#
# You can find information on editing this file and all the available options here:
# https://github.com/jellysquid3/sodium-fabric/wiki/Configuration-File
<<<<<<< HEAD
=======
=======
# This is the configuration file for Rubidium.
#
# You can find information on editing this file and all the available options here:
# https://github.com/CaffeineMC/sodium-fabric/wiki/Configuration-File
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
#
# By default, this file will be empty except for this notice.
