#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
<<<<<<< HEAD
#Fri Sep 26 03:06:00 PDT 2025
=======
<<<<<<< HEAD
#Thu Sep 25 23:15:18 PDT 2025
=======
#Sat Sep 20 20:51:17 PDT 2025
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
boolean.creative.enable_item_group_ferret=false
