#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
<<<<<<< HEAD
#Thu Sep 25 23:15:18 PDT 2025
=======
#Sat Sep 20 20:51:17 PDT 2025
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
boolean.creative.enable_item_group_ferret=false
