#A list of IDs to shut them up. Every element must be in "" and divided by , from one another.
#You can prevent RANDOM ticking of any block in the game. Be it vanilla or modded.
#E.G. ["minecraft:copper_block", "minecraft:bamboo"]
<<<<<<< HEAD
randomticks_blocks = [""]
=======
<<<<<<< HEAD
randomticks_blocks = [""]
=======
randomticks_blocks = ["minecraft:kelp"]
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff
#You can prevent TICKING of any block in the game. Be it vanilla or modded.
#USE AT YOUR OWN DISCRETION. YOU MUST KNOW WHAT YOU ARE DOING OR YOU CAN BREAK GAMEPLAY.
#E.G. ["minecraft:fire"]
ticks_blocks = [""]

