#A list of messages that if contained in a message will be stopped.
<<<<<<< HEAD
messages = ["You are using a beta version of Railcraft Reborn", "You are using a development version of Railcraft Reborn", "This game is using an alpha build of Ender IO"]
=======
<<<<<<< HEAD
messages = ["You are using a beta version of Railcraft Reborn", "You are using a development version of Railcraft Reborn", "This game is using an alpha build of Ender IO"]
=======
messages = ["You are using a beta version of Railcraft Reborn", "You are using a development version of Railcraft Reborn", "This game is using an alpha build of Ender IO", "Tough Beginnings", "Under The Moon", "Ice and Fire", "Terramity", "The Undead", "Discover Middle-Earth in Minecraft", "[First Aid] Press H For the tutorial]", "Press H for the tutorial", "Sake's Structures", "Beware the thunder bringing forth demonic arachnid overlords", "Spawnrates are configurable", "You are playing an alpha version of F&A. This release is not stable and you may encounter issues. You can find information on where to report problems on our modrinth or CurseForge pages."]
>>>>>>> 6206383c7f036264d908d290d17181ee59a27d6a
>>>>>>> f2ad6c1056497b98ca9b2e5dbc8b6247b5b15eff

