#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 26 03:57:52 PDT 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=10
shaderPack=Solas Shader V2.9b.zip
enableShaders=true
